### ISSUE TITLE
GT.M bindings/drivers for AIX System

### ISSUE THREAD

**Issue by josetesan** [dlwicksell/nodem#11]
Hi , good work beforehand.

We are currently using your module to provide support for our GT.M system on a Linux System, but there's a legacy system that still runs on AIX, in which we could not get this module working .

Do you know if it's easy/possible to build/get/have AIX bindings for this module ?

Thanks a lot.

**Comment by dlwicksell** [comment]
Hi Jose. Thank you for the kind words. I do not have an AIX system, nor do I have access to the AIX version of GT.M, so I cannot even test it at the moment.

What are the errors you are getting? If they are not something obvious, we can discuss options to get this working for you via email. Thank you.

**Comment by dlwicksell** [comment]
Hi Jose. 

Since I don't currently have any PowerPC (IBM POWER) hardware, nor do I have a license to run AIX, I can't actually do anything to help you on my own. You also haven't contacted me, so I haven't been able to explore other options for me to look at this for you. Since you have not responded to my last post, and my package.json file also specifies that Nodem runs on Linux, I'm going to close this issue.

However, should I ever gain any kind of access to an AIX machine, I will look at this issue for you. Thank you for your understanding.
